{"timestamp":"2025-08-28T14:55:41.772371","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-28T14:55:41.772950","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-28T14:55:42.211441","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ClientError","exc_value":"An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The Access Key Id you provided does not exist in our records.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":918,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1213,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/etl_dag.py","lineno":48,"name":"process"},{"filename":"/opt/airflow/dags/etl_dag.py","lineno":16,"name":"main"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":601,"name":"_api_call"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/context.py","lineno":123,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py","lineno":1074,"name":"_make_api_call"}],"is_group":false,"exceptions":[]}]}
